### PR TITLE
use dotenv instead of env.json

### PR DESCRIPTION
**Pull request by enigmartin**
Added `dotenv` package and the `.env` files that will be needed to avoid using hardcoded `env.json`, and added env files to `.gitignore` for security reasons. Added defaults as fallback and updated the Dockerfile to support as well. Also updated `README.md` so that users have a better idea of what `/data` is for, and how to do initial setup.

### CODE REVIEW

**Comment by space0blaster** [comment]
there's more places env.json is referenced, namely `chat.js` and `rag.js` to get the default model. there's also an endpoint on `server.js` where you can change the default model from `1b` to `3b` and the `model_v` variable needs to change to reflect that default change so the model choice persists. endpoint is `/models/create` line 822

**Comment by enigmartin** [comment]
Thought I'd committed those changes correctly - my bad. I'm not totally certain about the line 822 implementation, as I can't get through some other bugs to test a lot of stuff yet. Let me know how it looks/change it to your heart's content. Thanks

**Comment by space0blaster** [comment]
Going to test it locally but looks right, it just needs to update the default model_v env key and your last update looks right. What's the biggest bug stopping you from moving forward? I'll prioritize.

**Review by space0blaster — APPROVED** [review]
Thanks for this. Looks great. Pushing an composer file with these changes in a bit.

**Pull request merged**
